In [33]:
import numpy as np
from numpy import random
random.seed(0)

## DataTypes and attributes

#### numpy's main data type is ndarray.. nd mean n dimentional array

In [34]:
a1 = np.array([1,2,3,4,4,5,6,6])
a1

array([1, 2, 3, 4, 4, 5, 6, 6])

In [35]:
type(a1)

numpy.ndarray

In [36]:
a2 = np.array([[3,4,5,6,7],[3,4,5,6,7],[3,5,2,4,5]])
a2

array([[3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7],
       [3, 5, 2, 4, 5]])

In [37]:
a3 = np.array([[[3,4,5,6,7],[3,4,5,6,7],[3,5,2,4,5]], [[2,3,4,5,6],[3,4,5,6,6],[4,5,2,4,5]]])

In [38]:
a3

array([[[3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7],
        [3, 5, 2, 4, 5]],

       [[2, 3, 4, 5, 6],
        [3, 4, 5, 6, 6],
        [4, 5, 2, 4, 5]]])

![title](numpy-anatomy-of-a-numpy-array.png)

In [39]:
a1.shape

(8,)

In [40]:
a2.shape, a3.shape

((3, 5), (2, 3, 5))

In [41]:
a1.ndim #ndim mean n dimention which show the dimention

1

In [42]:
a2.ndim, a3.ndim

(2, 3)

In [43]:
a3.dtype

dtype('int32')

In [44]:
a2.size

15

In [45]:
# Create datafram from numpy array

import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2  3  4
0  3  4  5  6  7
1  3  4  5  6  7
2  3  5  2  4  5

In [46]:
one = np.ones((4,3))

In [47]:
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
zero = np.zeros((3,6))

In [49]:
zero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [50]:
rang_array = np.arange(0, 15, 2)
rang_array

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [60]:
random_int = np.random.randint(0, 10, size=(3,4))

In [61]:
random_int

array([[7, 2, 0, 0],
       [4, 5, 5, 6],
       [8, 4, 1, 4]])

In [59]:
random_array_2 = np.random.random((4,5))

In [54]:
random_array_2

array([[0.29753461, 0.05671298, 0.27265629, 0.47766512, 0.81216873],
       [0.47997717, 0.3927848 , 0.83607876, 0.33739616, 0.64817187],
       [0.36824154, 0.95715516, 0.14035078, 0.87008726, 0.47360805],
       [0.80091075, 0.52047748, 0.67887953, 0.72063265, 0.58201979]])

In [55]:
random_array_3 = np.random.rand(3, 2)

In [57]:
random_array_3

array([[0.53737323, 0.75861562],
       [0.10590761, 0.47360042],
       [0.18633234, 0.73691818]])

### seed fucntion will generate same random numbers

In [58]:
#Pseudo-random numbers
np.random.seed(0)
array_2 = np.random.random((3,4))
array_2

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

## Viewing arrays and matrics

In [62]:
np.unique(random_int)

array([0, 1, 2, 4, 5, 6, 7, 8])

In [63]:
random_int[0]

array([7, 2, 0, 0])

In [65]:
random_int[1]

array([4, 5, 5, 6])

In [66]:
random_int[:2]

array([[7, 2, 0, 0],
       [4, 5, 5, 6]])

In [67]:
random_int

array([[7, 2, 0, 0],
       [4, 5, 5, 6],
       [8, 4, 1, 4]])

In [73]:
random_int[:1 :1, :4]

array([[7, 2, 0, 0]])

In [89]:
a6 = np.random.randint(10, size=(2,2,4,4))

In [90]:
a6

array([[[[5, 6, 3, 2],
         [9, 8, 1, 4],
         [0, 8, 3, 9],
         [5, 5, 1, 7]],

        [[8, 6, 4, 7],
         [3, 5, 3, 6],
         [4, 7, 3, 0],
         [5, 9, 3, 7]]],


       [[[5, 5, 8, 0],
         [8, 3, 6, 9],
         [3, 2, 7, 0],
         [3, 0, 3, 6]],

        [[1, 9, 2, 9],
         [4, 9, 1, 3],
         [2, 4, 9, 7],
         [4, 9, 4, 1]]]])

In [76]:
a6.shape

(3, 2, 4, 5)

In [77]:
a6.ndim

4

In [94]:
a6[:1 :1, :1, 1:2]

array([[[[9, 8, 1, 4]]]])

## Manipulating and comparing arrays

In [95]:
a2, a3


(array([[3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7],
        [3, 5, 2, 4, 5]]),
 array([[[3, 4, 5, 6, 7],
         [3, 4, 5, 6, 7],
         [3, 5, 2, 4, 5]],
 
        [[2, 3, 4, 5, 6],
         [3, 4, 5, 6, 6],
         [4, 5, 2, 4, 5]]]))

In [96]:
a2 + a3

array([[[ 6,  8, 10, 12, 14],
        [ 6,  8, 10, 12, 14],
        [ 6, 10,  4,  8, 10]],

       [[ 5,  7,  9, 11, 13],
        [ 6,  8, 10, 12, 13],
        [ 7, 10,  4,  8, 10]]])

In [97]:
a2 -a3

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 1,  1,  1,  1,  1],
        [ 0,  0,  0,  0,  1],
        [-1,  0,  0,  0,  0]]])

In [98]:
a2 * a3

array([[[ 9, 16, 25, 36, 49],
        [ 9, 16, 25, 36, 49],
        [ 9, 25,  4, 16, 25]],

       [[ 6, 12, 20, 30, 42],
        [ 9, 16, 25, 36, 42],
        [12, 25,  4, 16, 25]]])

In [99]:
a2, a3

(array([[3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7],
        [3, 5, 2, 4, 5]]),
 array([[[3, 4, 5, 6, 7],
         [3, 4, 5, 6, 7],
         [3, 5, 2, 4, 5]],
 
        [[2, 3, 4, 5, 6],
         [3, 4, 5, 6, 6],
         [4, 5, 2, 4, 5]]]))

In [100]:
a3 * a2

array([[[ 9, 16, 25, 36, 49],
        [ 9, 16, 25, 36, 49],
        [ 9, 25,  4, 16, 25]],

       [[ 6, 12, 20, 30, 42],
        [ 9, 16, 25, 36, 42],
        [12, 25,  4, 16, 25]]])

In [101]:
a22 = np.random.randint(8, size=(3,4))

In [102]:
a22

array([[2, 5, 6, 5],
       [7, 2, 3, 1],
       [2, 7, 2, 6]])

In [103]:
a33 = np.random.randint(8, size=(4,3))

In [104]:
a33

array([[6, 4, 7],
       [2, 2, 3],
       [6, 6, 0],
       [5, 4, 7]])

In [105]:
a33 * a22

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

#### you can see in the above error that shape matters and we can do arthimetic operations on matrices which is the same shape

In [107]:
np.square(a2)

array([[ 9, 16, 25, 36, 49],
       [ 9, 16, 25, 36, 49],
       [ 9, 25,  4, 16, 25]], dtype=int32)

In [111]:
np.add(a2, a3)

array([[[ 6,  8, 10, 12, 14],
        [ 6,  8, 10, 12, 14],
        [ 6, 10,  4,  8, 10]],

       [[ 5,  7,  9, 11, 13],
        [ 6,  8, 10, 12, 13],
        [ 7, 10,  4,  8, 10]]])